version: '2'
services:
    hashfu-mongodb:
        container_name: hashfu-mongodb
        image: mongo:3.2.10
        ports:
            - "27017:27017"
        # volumes:
        #     - ~/volumes/jhipster/hashfu/mongodb/:/data/db/
